DELIMITER $$
 
CREATE PROCEDURE DELETE_INSTRUCTOR(IN p_ID VARCHAR(25))
BEGIN

START TRANSACTION;

SELECT @flag:=COUNT(ID) FROM  instructor WHERE ID = p_ID;
DELETE FROM teaches WHERE ID = p_ID;
COMMIT;
DELETE FROM advisor WHERE s_ID = p_ID;
COMMIT;
DELETE FROM instructor WHERE ID = p_ID;

IF (@flag = 0) 
THEN ROLLBACK;
ELSE COMMIT;
END IF;

END$$

DELIMITER ;
